### ISSUE TITLE
Terminology review

### ISSUE THREAD

**Issue by italobusi** [danielkinguk/transport-nbi#17]
Review the Use Case Description Internet-Draft and refresh the terminology section, like 'service model' and 'UNI'

https://github.com/danielkinguk/transport-nbi/blob/master/Meetings/2017-11-11-17-IETF100/minutes-transport-nbi-dt-2017-11-11-17-ietf100.md

**Comment by italobusi** [comment]
Comments to the Use Case Description Internet-Draft will be reported and addressed during the development of the Merged Internet-Draft

**Comment by danielkinguk** [comment]
[draft-ietf-ccamp-transport-nbi-use-cases-01-sb.docx](https://github.com/danielkinguk/transport-nbi/files/1772087/draft-ietf-ccamp-transport-nbi-use-cases-01-sb.docx)

**Comment by danielkinguk** [comment]
The above file are the comments from Sergio.

**Comment by italobusi** [comment]
@danielkinguk : to update the merged draft accordingly

**Comment by danielkinguk** [comment]
[
[Terminology v1.txt](https://github.com/danielkinguk/transport-nbi/files/1775904/Terminology.v1.txt)
]

**Comment by danielkinguk** [comment]
[Terminology v1.txt](https://github.com/danielkinguk/transport-nbi/files/1775905/Terminology.v1.txt)

**Comment by italobusi** [comment]
Proposed comments resolution merged to pull request #16
