### ISSUE TITLE
Review of OpenConfig model

### ISSUE THREAD

**Issue by italobusi** [danielkinguk/transport-nbi#20]
Review the OpenConfig OTN model to see if its relevent for the DT work

In particular, check how in OpenConfig it is possible to configure the mapping of client services over OTN

https://github.com/danielkinguk/transport-nbi/blob/master/Meetings/2017-11-11-17-IETF100/minutes-transport-nbi-dt-2017-11-11-17-ietf100.md

**Note - assigned to Dieter**

**Comment by italobusi** [comment]
To be discussed during the face-to-face DT meeting at IETF 101

**Comment by italobusi** [comment]
As discussed during the face-to-face meeting (March 21, 2018):

Review in details the OpenConfig model to check if there is something which can be used by the TNBI DT or confirm that there is nothing that can be reused

**Comment by danielkinguk** [comment]
No impact on our work.
