### ISSUE TITLE
Review TIP and check YANG usage and applicability to NBI discussion

### ISSUE THREAD

**Issue by danielkinguk** [danielkinguk/transport-nbi#23]
TIP working on YANG models for an Optical Abstraction Interface (OAI).

**Comment by italobusi** [comment]
DT call on June 6:

Daniel is working on a paper on this topic and he will share some information in the coming days to the DT

**Comment by danielkinguk** [comment]
No major impact on our work. We can present new I-D to relevant TIP members after next version.
