### ISSUE TITLE
Prepare the slides for the IETF 101 CCAMP WG

### ISSUE THREAD

**Issue by italobusi** [danielkinguk/transport-nbi#27]

**Comment by XYBPHIL** [comment]
two sildes for the dynamic restoration for reference.
[Controller based dynamic restoration.pptx](https://github.com/danielkinguk/transport-nbi/files/1787619/Controller.based.dynamic.restoration.pptx)

**Comment by italobusi** [comment]
Slides prepared and presented at the CCAMP WG session
