### ISSUE TITLE
Complete ODU2 and EPL Service Examples at MPI1

### ISSUE THREAD

**Issue by italobusi** [danielkinguk/transport-nbi#31]
Updated JSON code examples to setup ODU2 and EPL Services @ MPI1 to complete the pending action points identified in pull request #29 and pull request #32 

Action postponed for future update:
- Align the code with the latest versions of the TE Topology and Tunnel models
- Update the REST operation to avoid replacing the whole te datastore
- Remove for the ietf-otn-tunnel:payload-treatment attribute: pending OTN tunnel model update https://github.com/haomianzheng/IETF-ACTN-YANG-Model/issues/6
- Remove the src-tpn, src-tsg, src-tributary-slot-count, src-tributary-slots, dst-tpn, dst-tsg, dst-tributary-slot-count and dst-tributary-slots attributes/containers: pending OTN tunnel model update https://github.com/haomianzheng/IETF-ACTN-YANG-Model/issues/7
- Check with TE Tunnel model authors how to set the te-label direction
- Add the te-topology-identifier information: pending pull request #10 
- Check with TE Tunnel model authors why the source and destination attributes are defined as ip-address and not as te-node-id: see https://github.com/ietf-mpls-yang/te/pull/35

**Status:**
- [x] Pending merge of pull request #78

**Comment by sergiobelotti** [comment]
Check the need for the ietf-otn-tunnel:payload-treatment attribute
Added comment in haomianzheng/IETF-ACTN-YANG-Model#6

**Comment by italobusi** [comment]
Actions planned for IETF 102 completed with pull request #32 

Pending actions planned for IETF 103

**Comment by italobusi** [comment]
Closed with pull request #78
