### ISSUE TITLE
Clean-up the DT github structure

### ISSUE THREAD

**Issue by italobusi** [danielkinguk/transport-nbi#34]
There is no need to archive in github the old versions of the reference files: only to the latest version of the files needs to be stored.
Old versions can be tagged as revisions.

**Comment by italobusi** [comment]
The 02 version has been tagged:

https://github.com/danielkinguk/transport-nbi/releases/tag/02

**Comment by italobusi** [comment]
The github structure has been changed as proposed

@GianmarcoBruno : are you ok with the new structure?

**Comment by GianmarcoBruno** [comment]
OK I agree with the new structure
