### ISSUE TITLE
Full Review of draft-ietf-ccamp-transport-nbi-app-statement-02 required

### ISSUE THREAD

**Issue by danielkinguk** [danielkinguk/transport-nbi#35]
Especially need to remove any text that duplicates discussion from the TE Tutorial

**Comment by italobusi** [comment]
@danielkinguk : do a first review then Italo will do another review cycle

**Comment by italobusi** [comment]
@danielkinguk : is the review you have done for the -03 version complete or would you like to do another review cycle before the next IETF?

**Comment by danielkinguk** [comment]
Reviewed and submitted for IETF 103.
