### ISSUE TITLE
Finalize text about administration of inter-domain Links

### ISSUE THREAD

**Issue by italobusi** [danielkinguk/transport-nbi#63]
Add to the text in section 4.2 a reference to an existing RFC describing the administrative issues

Add also appropriate text to the Security Considerations section, if needed

**Comment by italobusi** [comment]
This is the current text in section 4.2:

> The MDSC should be capable of stitching together  the abstracted topologies provided by each PNC to build its own view of the multi-domain network topology. This topology knowledge may require proper oversight, including the application of local policy, configuration methods, and the application of a trust model. Methods of how to manage these aspects are out of scope for this document, but recomandations are provided in the Security section of this document

**Comment by danielkinguk** [comment]
I think the latest Security Section text addresses this issue now.

**Comment by italobusi** [comment]
See: https://github.com/danielkinguk/transport-nbi/files/3451228/draft-ietf-ccamp-transport-nbi-app-statement-05-English-Review-DK-Comments.docx
