### ISSUE TITLE
Finalize the text on segment protection

### ISSUE THREAD

**Issue by italobusi** [danielkinguk/transport-nbi#64]
Need to review and re-concile the two text proposals for section 5.3.2 (Segmented Protection)

**Comment by italobusi** [comment]
@haomianzheng : please check latest text proposal in 550ff06a5753bbf8c0f6b3cf69f2d6ab10f83339

**Comment by haomianzheng** [comment]
> @haomianzheng : please check latest text proposal in [550ff06](https://github.com/danielkinguk/transport-nbi/commit/550ff06a5753bbf8c0f6b3cf69f2d6ab10f83339)

I have reviewed the updated text in 5.3.2, and have no other comments.
