### ISSUE TITLE
Minor editorial issues

### ISSUE THREAD

**Issue by michael-scharf** [danielkinguk/transport-nbi#67]
Reviewed version: Proposal for draft-ietf-ccamp-transport-nbi-app-statement-06 as of June 14

I have found some minor editorial issues:

Abstract

* "using standardized data models (e.g. YANG) and _an_ appropriate protocol (e.g., RESTCONF)"

Table of Content

* Use of capital letters should be consistent

* I am not sure if Section 4.3.3 should perhaps be called "Other OTN _Client_ Services" ?

Section 1

* "Internet service backhauling_,_"

Section 1.1

* "are preconfigured and _use_ mechanisms"

Section 2

* It may be useful to add some further acronyms, such as LTP, TTP and IIL. BTW, as far as I can see, the acronyms TTP and IIL are currently not expanded in the text.

Section 4.1

* "_We_ also assume" (or maybe even better: "This memo also assumes")

Section 4.3

* s/The control of different adaptations inside IP routers/The processing inside IP routers/
  (The term "adaptation" is IMHO not used for routers)

Section 4.4

* "the R1-S3 and R8-S18 access links will be __ multi-function access links", 

Section 4.5

* The first sentence in the last paragraph "Since in these..." seems broken.

**Comment by italobusi** [comment]
Just uploaded an updated I-D with proposed resolution: e3959855de86679f515f20e07afdffbe5b41aaa6

Some comments are accepted, other reconciled with Dieter's comments and other still open for discussion

**Comment by italobusi** [comment]
**2019-6-24 DT Call**

Comments reviewed and resolved: https://github.com/danielkinguk/transport-nbi/blob/master/Meetings/2019-06-24/minutes-transport-nbi-dt-2019-06-24.md

See updated document: https://github.com/danielkinguk/transport-nbi/commit/e3959855de86679f515f20e07afdffbe5b41aaa6
