### ISSUE TITLE
Abstract could better describe the value proposition

### ISSUE THREAD

**Issue by michael-scharf** [danielkinguk/transport-nbi#68]
Reviewed version: Proposal for draft-ietf-ccamp-transport-nbi-app-statement-06 as of June 14

The abstract is already quite long, but IMHO it does not describe well the actual content and value proposition of the document.

For instance, the first paragraph of the abstract could be shortened or even removed (if so, maybe the Introduction would need to be expanded).

Additional text on the actual content could be added along the lines of "This document contains a number of worked examples to illustrate how existing YANG models can be used. Corresponding JSON fragments are also provided."

**Comment by italobusi** [comment]
**2019-06-24 DT Call**

@italobusi , @danielkinguk : propose text changes to the abstract accordingly

**Comment by italobusi** [comment]
Proposed new abstract:

> This document provides an analysis of the applicability of the YANG models defined by the IETF (Traffic Engineering Architecture and Signaling (TEAS) and Common Control and Measurement Plane (CCAMP) WGs in particular) to support ODU transit services, Transparent client services and EPL/EVPL Ethernet services over OTN single and multi-domain network scenarios.
> 
> This document also describes how existing YANG models can be used through a number of worked examples and JSON fragments.
> 

Proposed rephrasing of the initial paragraphs of the Introduction:

> Transport network domains, including Optical Transport Network (OTN) and Wavelength Division Multiplexing (WDM) networks, are typically deployed based on a single vendor or technology platforms. They are often managed using proprietary interfaces to dedicated Element Management Systems (EMS), Network Management Systems (NMS) and increasingly Software Defined Network (SDN) controllers.
> 
> Support of packet connectivity services over transport network domains are critical for a wide range of applications and services, including data center and LAN interconnects, Internet service backhauling, mobile backhaul and enterprise Carrier Ethernet services. A clear goal of operators is to automate the setup of connectivity services across multiple transport network domains that may utilize different technologies.
> 
> A well defined common open interface to each domain controller or management system is required for network operators to control multi-vendor and multi-domain networks and also enable coordination and automation of service provisioning. This is facilitated  by using standardized data models (e.g., YANG models), and an appropriate protocol (e.g., RESTCONF [RFC8040]).

@michael-scharf , @danielkinguk : what do you think?

**Comment by italobusi** [comment]
See: https://github.com/danielkinguk/transport-nbi/files/3447099/draft-ietf-ccamp-transport-nbi-app-statement-ib-2019-07-30.docx

I have also proposed text changes to the Introduction section to keep consistency and not to loose valuable information

@michael-scharf , @danielkinguk : what do you think?

**Comment by michael-scharf** [comment]
Works for me

**Comment by italobusi** [comment]
**2019-07-31 DT Call**

Agreed to close the issue
