### ISSUE TITLE
Explicit statements on the outcome of the analysis?

### ISSUE THREAD

**Issue by michael-scharf** [danielkinguk/transport-nbi#69]
Reviewed version: Proposal for draft-ietf-ccamp-transport-nbi-app-statement-06 as of June 14

Section 5 "analyses how the IETF YANG models can be used at the MPIs, between the MDSC and the PNCs, to support the scenarios described in section 4."

To me, this raise a question: What is the outcome of the analysis? At least in my understanding of the term "analysis" (as a non-native speaker), I would expect some summary statement to which extent the YANG models can handle indeed the presented scenarios. Probably they are applicable and there are no major gaps, right? But are there other outcomes of the analysis? For instance, is a certain use of the models required to handle the scenarios, e.g., are certain attributes mandatory? Are attributes not needed or not useful in these cases? Are there multiple choices for some requirements (an example may be Section 5.1.4)?

For the given title, I would actually expect some summary or maybe even some recommendation or lessons learnt. Otherwise, the document would merely be a list of worked examples.

**Comment by italobusi** [comment]
**2019-06-24 DT Call**

@italobusi : propose text for a conclusion section

**Comment by italobusi** [comment]
@michael-scharf : please review section 8 proposed in the latest draft https://github.com/danielkinguk/transport-nbi/commit/550ff06a5753bbf8c0f6b3cf69f2d6ab10f83339

**Comment by michael-scharf** [comment]
Actually, I am not a big fan of a "conclusion" section. And, specifically, I believe a section after the IANA considerations is pretty useless in reality.

I was actually thinking about a summary statement much earlier in the document.

For instance, the last paragraph of Section 1 could be expanded as follows:

This document examines the applicability of the YANG models being defined by IETF (Traffic Engineering Architecture and Signaling (TEAS) and Common Control and Measurement Plane (CCAMP) WGs in particular) to support Optical Transport Networks (OTN) single and multi-domain scenarios. **The document confirms that the IETF YANG models defined in [RFC8345], [TE TOPO], [OTN TOPO], [CLIENT TOPO], [TE TUNNEL], [PATH COMPUTE], [OTN TUNNEL] and [CLIENT SIGNAL] can be used together to control a multi domain OTN network to support different types of multi domain services such as ODU transit services, Transparent client services and EPL/EVPL Ethernet services over a multi domain OTN connection.**

There are probably also other places in the document where such a summary could be stated without requiring a new section.

**Comment by italobusi** [comment]
**2019-07-03 DT Call**

Ok to move the text to section 1 and also confirms, as a conclusion, that also ONF requirements are satisfied

**Comment by michael-scharf** [comment]
I think there is now some duplication between section 1 and 1.1. Apart from the editorial duplication, the statement is what I was looking for.

**Comment by italobusi** [comment]
@michael-scharf : Good point

To avoid text duplication, we can move the last sentence in section 1 at the end of section 1.1 and modify as:

> The analysis provided in this document confirms that the IETF YANG models defined in [RFC8345], [TE TOPO], [OTN TOPO], [CLIENT TOPO], [TE TUNNEL], [PATH COMPUTE], [OTN TUNNEL] and [CLIENT SIGNAL] can be used together to control a multi domain OTN network to support different types of multi domain services such as ODU transit services, Transparent client services and EPL/EVPL Ethernet services over a multi domain OTN connection, satisfying also the requirements in [ONF TR-527].

**Comment by italobusi** [comment]
**2019-07-23 DT Meeting**

Agreed the text in https://github.com/danielkinguk/transport-nbi/issues/69#issuecomment-508388246

@italobusi : update the draft accordingly

**Comment by italobusi** [comment]
Added to the latest draft: ff62c1a02bb86542a9144a293803869a38ec55f8
