### ISSUE TITLE
Organization of the content (in particular for assumptions)

### ISSUE THREAD

**Issue by michael-scharf** [danielkinguk/transport-nbi#70]
Reviewed version: Proposal for draft-ietf-ccamp-transport-nbi-app-statement-06 as of June 14

The differences between scenario descriptions, modeling assumptions and use case details are somewhat blurred in the document and are spread over many different sections. For instance, in Section 5 assumptions are mentioned or even repeated quite a number of times and this results in many cross-references back to section 4. Also, section 5 has own statements about the scope (e.g., beginning of 5.2). While I am fine with the content, I find the order of presentation and the introduction of assumptions sometimes confusing.
 
It is not entirely clear to me if reordering some content would simplify the text, but I recommend to think at least about where to introduce what.

For instance, one could perhaps give up the top-level separation between description (section 4) and analysis (section 5) and instead have top-level sections on use cases. Inside each use case, first the scenario would be described and then it would be analyzed. Perhaps this would reduce the number of required cross-references. Yet, this would be a disruptive change and I just mention this idea for the sake of completeness.

A number of smaller changes would probably be doable without disrupting the table of content:

* To somebody who reads the document for the first time, the content of Section 1.2 is hardly understandable so early in the document. I'd recommend to move this text after the introduction of the architecture and scenarios.

* Maybe add at the beginning of each subsection in Section 5 a list of other Sections (most notably in 4) with the underlying assumptions?

**Comment by italobusi** [comment]
**2019-06-24 DT call:**

Check where to move the assumptions in section 1.2 within the document

Review section 5 and see if there is a way to make it easier to summarize where to find the underlying assumptions

**Comment by italobusi** [comment]
@michael-scharf : please check changes to section 5 in the latest draft: https://github.com/danielkinguk/transport-nbi/commit/550ff06a5753bbf8c0f6b3cf69f2d6ab10f83339

Section 1.2 has been removed

**Comment by michael-scharf** [comment]
Works for me
