### ISSUE TITLE
JSON examples in main body???

### ISSUE THREAD

**Issue by michael-scharf** [danielkinguk/transport-nbi#72]
Reviewed version: Proposal for draft-ietf-ccamp-transport-nbi-app-statement-06 as of June 14

I wonder whether to move the JSON examples to the main body of the document. Somewhat the actual examples seem one of the key contributions of the document, and the main body refers to the JSON code quite a bit. Just as a thought... This issue can also just be closed without any action (albeit it would be a major reorganization of content).

**Comment by italobusi** [comment]
**2019-06-24 DT call**

It is a matter of personal taste. We will proceed under the assumption to keep the JSON code in the appendix and see if there are other opinions.

**Comment by italobusi** [comment]
@italobusi : Check with the DT mailing list if there are other opinions

**Comment by italobusi** [comment]
**2019-10-02 DT Call**

Agreement to leave the JSON code examples in the appendix since it is quite a lot of code
