### ISSUE TITLE
Sentence too long in section 4.1

### ISSUE THREAD

**Issue by italobusi** [danielkinguk/transport-nbi#73]
The following sentence in section 4.1 is too long:

> It is worth noting that the functional split between the MDSC and the PNCs of functionality at the MPI in the ACTN architecture between the MDSC and the PNCs is equivalent/analogous to the functional split of functionality which is assumed for the ONF T-API interface when used between a multi-domain controller and the domain controllers, as described in the ONF T-API multi-domain use cases [ONF TR-527], as well as at the MEF PRESTO interface between the Service Orchestration Functionality (SOF) and the Infrastructure Control and Management (ICM) in the MEF LSO Architecture [MEF 55].

Need to provide shorter sentences instead

**Comment by danielkinguk** [comment]
Fixed in latest Word document.

**Comment by italobusi** [comment]
See: https://github.com/danielkinguk/transport-nbi/files/3451228/draft-ietf-ccamp-transport-nbi-app-statement-05-English-Review-DK-Comments.docx
