### ISSUE TITLE
Editorial: rephrasing text about network configuration

### ISSUE THREAD

**Issue by italobusi** [danielkinguk/transport-nbi#75]
Rephrase the current text on network configuration: it appears in multiple places within the document

See for example the text in section 4.3.1:

> The MDSC figures out that it needs to establish an ODU2 transit service between the access links on S3 and S18, which belong to different PNC domains (multi-domain service request). It also determines the network configurations requests to be sent to its underlying PNCs, at the MPIs, to coordinate the setup of a multi-domain ODU2 connection segments between the access links on S3 and S18

**Comment by danielkinguk** [comment]
Fixed in Word version.

**Comment by italobusi** [comment]
See: https://github.com/danielkinguk/transport-nbi/files/3451228/draft-ietf-ccamp-transport-nbi-app-statement-05-English-Review-DK-Comments.docx

**Comment by danielkinguk** [comment]
Still an open issue.

**Comment by italobusi** [comment]
See review comments: https://github.com/danielkinguk/transport-nbi/pull/66#issuecomment-542185995
