### ISSUE TITLE
Complete validation of JSON code examples

### ISSUE THREAD

**Issue by italobusi** [danielkinguk/transport-nbi#80]
The following JSON code examples need to be validated:
- mpi1-eth-topology.json
- mpi1-epl-service-config.json

**Comment by GianmarcoBruno** [comment]
Hi Italo,
I just uploaded the validated mpi1-epl-service-config.json

**Comment by GianmarcoBruno** [comment]
Uploaded mpi1-eth-topology.json too.
The ethtetopo needs a small fix too - a namespace qualifier was missing at line 303.

**Comment by italobusi** [comment]
Closed with pull request #81
